### ISSUE TITLE
Fix order of config options in wizard

### ISSUE THREAD

**Issue by JasmineLowen** [TheBiochemic/tickets-rs#1]
Hey!

First of all: That's a cool project! It has a really cool look and feel to it!

I noticed a little thing when testing the program: The order of the config options change if you press the available options multiple times. Here is a short demo of what I mean:

![tickets-rs](https://user-images.githubusercontent.com/26892280/211213456-0e44de3d-962a-430c-bfa6-98458be73576.gif)

I think this issue is related to the use of a `HashMap` which has non-determined order of iteration. I think, I can come up with a very small fix.

**Comment by TheBiochemic** [comment]
Thanks a lot ^^
In general i have a few things where the order is random from the hashmap, such as the sidepanels item ordering, but either me or someone else will probably provide a fix for it, since you demonstrated, that i'ts not hard to do :)

In general i wanted to bring tickets.rs into a usable state until the end of last year, which almost worked :D
Currently working on my next rust project, but whenever there is something major to do, i will come back to it, since i use it everyday myself ^^

Already merged your PR, thanks for the ticket ^^
